### PR TITLE
Add `ember-cli-template-lint`

### LINKED ISSUE #3: Setup linting and style enforcement.
_From @Alonski on April 24, 2017 10:42_

We should be using ESLint and Prettier +- Standard to format our Javascript.
If we need custom CSS we can use stylelint and stylefmt.
Maybe using SASS instead of plain CSS

_Copied from original issue: Alonski/realworld-ember#10_

### PR DESCRIPTION
**Pull request by alexlafroscia**
Closes #3

### CODE REVIEW

**Comment by Alonski** [comment]
Hmm how did you get this running?

**Comment by alexlafroscia** [comment]
What do you mean? I just installed the addon.

```bash
ember install ember-cli-template-lint
```

**Comment by Alonski** [comment]
I was getting the error that I linked to on the issue. Are you on an OS other than Windows? Maybe it's an OS issue.

**Comment by alexlafroscia** [comment]
Yeah, I'm using a Mac. Could be an OS issue, I dunno.

Since the build is passing, can you review the PR @Alonski, assuming you're OK with this change?

**Pull request merged**
